# -*- coding: utf-8 -*-
"""MAIRA_3B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8juagr604PqUvMmjLGBTTRFNoiNxht3

3B - exiba no mapa os pontos de
uma das bases de dados abertos da
prefeitura de Curitiba (se necessário filtre
para 2000 pontos)
"""

import folium
!pip install geopandas
import geopandas as gpd

"""Exibindo localização de academias de artes marciais em Curitiba. Dados filtrados do arquivo Base de Alvarás, disponível em https://dadosabertos.curitiba.pr.gov.br/"""

academias_artes_marciais = 'academias_geocode.geojson'

df = gpd.read_file(academias_artes_marciais)

#df

med_lat = df.geometry.y.mean()
med_lon = df.geometry.x.mean()

map = folium.Map(location=[med_lat, med_lon],
                 tiles='OpenStreetMap',
                 zoom_start=12)

for idx, row in df.iterrows():
    if row['geometry'] is not None:
        folium.Marker(
            location=[row['geometry'].y, row['geometry'].x],
            tooltip=row['NOME_FANTASIA'],
            icon=folium.Icon(color='orange', icon='certificate')
        ).add_to(map)

map